# Generated by Django 4.2.29 on 2026-03-22 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaign_manager", "0002_spell_characterspell"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("ally", "Ally"),
                            ("rival", "Rival"),
                            ("mentor", "Mentor"),
                            ("sibling", "Sibling"),
                            ("romantic", "Romantic Interest"),
                            ("debt", "Debt Owed"),
                            ("neutral", "Neutral"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                (
                    "sentiment_score",
                    models.IntegerField(
                        default=0,
                        help_text="Current overall sentiment (updated based on events)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_initiated",
                        to="campaign_manager.character",
                    ),
                ),
                (
                    "to_character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_received",
                        to="campaign_manager.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelationshipEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="What happened (e.g., 'Saved from ambush', 'Betrayed during negotiation')"
                    ),
                ),
                (
                    "sentiment_change",
                    models.IntegerField(
                        help_text="Positive = improves relationship, Negative = worsens it"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relationship_events",
                        to="campaign_manager.encounter",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="campaign_manager.characterrelationship",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="characterrelationship",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("from_character", models.F("to_character")), _negated=True
                ),
                name="prevent_self_relationship",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="characterrelationship",
            unique_together={("from_character", "to_character")},
        ),
    ]
